version: '2'
services:
  postgres:
    image: mdillon/postgis
    environment:
    - POSTGRES_DB={{cookiecutter.project_slug}}
    - POSTGRES_USER={{cookiecutter.project_slug}}
    - POSTGRES_PASSWORD={{cookiecutter.project_slug}}
    ports:
    - "5432:5432"