version: '2'
services:
  postgres:
    image: mdillon/postgis
    environment:
    - POSTGRES_DB={{cookiecutter.project_slug}}
    - POSTGRES_USER={{cookiecutter.project_slug}}
    - POSTGRES_PASSWORD={{cookiecutter.project_slug}}
    ports:
    - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - .:/home/app/